### ISSUE TITLE
Cheatsheet request: screen

### ISSUE THREAD

**Issue by nathanv** [rstacruz/cheatsheets#664] opened 2018-07-24 13:25 UTC
I use screen but I forget tonnes of the commands all the time. Would love a quality cheat sheet!

**Comment by ondrejhlavacek** [comment] 2018-08-14 15:04
already here - https://github.com/rstacruz/cheatsheets/issues/526

**Comment by chadwithuhc** [comment] 2018-12-05 00:19
Duplicate of #526

**Closed by chadwithuhc** 2018-12-05 00:19 UTC
