### ISSUE TITLE
Cheatsheet request: SVG

### ISSUE THREAD

**Issue by bbuck** [rstacruz/cheatsheets#646] opened 2018-07-23 18:39 UTC
SVG, specifically `path` and it's `d` attribute can be quite cryptic. Info is easy to find in documentation but since you've got "cheatsheets" a quick reference would be great.

I'll take a look at what it takes to build a cheatsheet and may make an initial pass when I have some time.

**Comment by chadwithuhc** [comment] 2018-12-05 00:18
Duplicate of #569

**Closed by chadwithuhc** 2018-12-05 00:18 UTC
