### ISSUE TITLE
Cheatsheet request: PHP

### ISSUE THREAD

**Issue by psion** [rstacruz/cheatsheets#640] opened 2018-07-23 15:31 UTC
PHP and top frameworks/tools for it:
Symfony, Zend Framework (whatever number they are on now), Laravel, Composer, etc

**Comment by ricardobarantini** [comment] 2018-07-23 21:45
+1

**Comment by jkingwg** [comment] 2018-08-02 13:16
+1

**Comment by chadwithuhc** [comment] 2018-12-05 00:16
Duplicate of #75 
Duplicate of #102 
Duplicate of #212

**Closed by chadwithuhc** 2018-12-05 00:16 UTC
