### ISSUE TITLE
Friendly print/pdf

### ISSUE THREAD

**Issue by nhatn1507** [rstacruz/cheatsheets#247] opened 2017-11-08 14:01 UTC
It would be awesome if users can generate each page into a pdf and print it without losing the page's great structure.

**Comment by bahsoun** [comment] 2017-12-02 22:21
Hello
You may inject the following CSS to the page and print it as PDF file
[devHintsIo.txt](https://github.com/rstacruz/cheatsheets/files/1524304/devHintsIo.txt)

@media print {
h2 {
width: 86%;
max-width: 86%;
display: block;
}
.h3-section-list > .h3-section {
width: 86%;
max-width: 86%;
}
.h3-section-list.-three-column > .h3-section {
width: 45%;
max-width: 45%;
}
.h3-section-list > .h3-section,
.h3-section-list.-three-column > .h3-section {
page-break-inside: avoid;
box-sizing: border-box;
position: unset !important;
display: inline-block;
float: left !important;
margin-left: 20px;
}
.h2-section {
page-break-inside: avoid;
}
footer {
display: none;
}
}

**Comment by chadwithuhc** [comment] 2018-11-19 22:32
Duplicate of #113

**Closed by chadwithuhc** 2018-11-19 22:32 UTC
Labels: bug
