### ISSUE TITLE
Add LICENSE / COPYING.md

### ISSUE THREAD

**Issue by jehb** [rstacruz/cheatsheets#592] opened 2018-07-03 13:44 UTC
I couldn't tell from your CONTRIBUTING doc what license this project is actually under, or what license my contributions would be under if I added to it. It seems to be missing from the project README and the actual website too.

**Comment by sheldonhull** [comment] 2018-07-17 15:37
@rstacruz  this is a great resource, thanks so much for it. I wanted to leverage some of this for a personal cheatsheet for some things more specific to me. I forked, but then noticed the same thing. No License.md/txt seems to be included with MIT license. Could you consider adding if possible, and in the meantime confirm it's ok to fork and use for my own copy? 

Some of the stuff I'll hopefully contribute back, but some of it is more specific stuff that wouldn't be the best for a global cheat sheet (ie, specific powershell module cheatsheets etc)

**Comment by sheldonhull** [comment] 2018-07-18 23:33
@jehb  looks like I found the answer. It's in the package.json!  Thanks to @rstacruz  for implementing this. Going to have fun working with this. Suggest you close this issue due to duplicate of #301

**Comment by 0x326** [comment] 2019-07-07 16:09
@sheldonhull This repo still should contain a copy of the MIT license text

**Comment by mdtrooper** [comment] 2019-11-05 18:36
Is it under MIT license?

**Comment by jhabdas** [comment] 2019-11-14 10:56
> Is it under MIT license?

At this point you'd have to ask 185 contributors. As it stands everyone owns each change and the website, which is clearly advertising, is making small crimes if the money isn't being equitably distributed across all contributors.

<img width="541" alt="Screen Shot 2019-11-14 at 18 55 53" src="https://user-images.githubusercontent.com/57753420/68851227-7f031100-0710-11ea-8f81-f019889d0dde.png">

**Comment by darioseidl** [comment] 2021-10-05 12:07
> Is it under MIT license?

Yes, the owner of this repo [said here that it was under MIT license](https://github.com/rstacruz/cheatsheets/issues/301) and the package.json file specified that too at least since 2017 from what I can see in the git history. 

> At this point you'd have to ask 185 contributors. As it stands everyone owns each change and the website, which is clearly advertising, is making small crimes if the money isn't being equitably distributed across all contributors.

I don't think that's true. If, in the beginning of this repository, there was no license specified (I'm not sure if the package.json was there from the beginning), I believe that each contributor would have copyright for their contributions, but that would only apply to contributions added before the license was specified. And if nobody files for a copyright violation, I think it is okay to assume that they are okay with their contributions being used in the way they are used, because they contributed with the intention of adding content to open source cheat sheets. I'm not a lawyer, but that's what I would assume. If none of the contributors complain, I don't see a problem. If some contributor thinks that the website showing his contributions is violating his copyright or that he's entitled to some ad money they should contact the owner of the website and discuss that with them.

Anyway, this is a cool project and it would be great if further licensing issues could be avoided by adding a license file. There exists already a [pull request](https://github.com/rstacruz/cheatsheets/pull/1613) for that. @rstacruz could you accept the pull request?

**Closed** 2021-10-07 10:52 UTC
Labels: bug
