### ISSUE TITLE
Cheatsheet request: MongoDB

### ISSUE THREAD

**Issue by eliot84** [rstacruz/cheatsheets#559] opened 2018-06-09 17:56 UTC
Congrats on your site it is awesome. Wish there was a MongoDB Cheatsheet guide. I am currently using it with my node.js projects.

**Comment by chadwithuhc** [comment] 2018-12-04 23:43
It's in the requests for now, but someday!

Duplicate of #194

**Closed by chadwithuhc** 2018-12-04 23:43 UTC
