### ISSUE TITLE
Windows CLI Cheatsheets

### ISSUE THREAD

**Issue by dellasorte** [rstacruz/cheatsheets#515] opened 2018-04-29 22:34 UTC
Hi all. First of all thank all cobtributors and site creators. Cheatsheet are really helpful even for experienced developers. 

I didn't saw cheatsheet for windows command-line (cmd) and powershell CLIs . Is there any reason to ignore them? Guess it will be helpful for someone too.

**Comment by gretel** [comment] 2018-04-30 10:41
@dellasorte could you point to the ones you are referring to please?

**Comment by chadwithuhc** [comment] 2018-11-19 23:36
Duplicate of #193

**Closed by chadwithuhc** 2018-11-19 23:36 UTC
