### ISSUE TITLE
Cheatsheet Enhancement: Sqlite 

### ISSUE THREAD

**Issue by sytabaresa** [rstacruz/cheatsheets#731] opened 2018-08-07 02:06 UTC
Hello,
I see that bash cheatsheet don't have a very common for loop mode for multiline commands:
```bash
for elem in $(some-command); do
  echo $elem
done
```
and for single element for loop:

```bash
for elem in a b c; do
  echo $elem
done
```
maybe this can be very educational for the readers.

thank you

**Comment by chadwithuhc** [comment] 2018-12-06 20:14
Duplicate of #675

**Closed by chadwithuhc** 2018-12-06 20:14 UTC
Labels: enhancement, new sheet
