### ISSUE TITLE
Cheatsheet request: Kubernetes

### ISSUE THREAD

**Issue by cnowacek** [rstacruz/cheatsheets#647] opened 2018-07-23 18:53 UTC
kubectl, example spec.yaml snippets, etc.

**Comment by fmoliveira** [comment] 2018-08-09 14:41
@rstacruz This is duplicate of https://github.com/rstacruz/cheatsheets/issues/617

@cnowacek I've added your suggestions in the original kubectl request mentioned above 😃

**Comment by chadwithuhc** [comment] 2018-12-05 00:19
Duplicate of #324

**Closed by chadwithuhc** 2018-12-05 00:19 UTC
