### ISSUE TITLE
Cheatsheet request: Kotlin

### ISSUE THREAD

**Issue by mustapha-hadid** [rstacruz/cheatsheets#582] opened 2018-06-26 20:27 UTC
Kotlin is the second most loved language in [Stackoverflow survey 2018](https://insights.stackoverflow.com/survey/2018#most-loved-dreaded-and-wanted)!

**Comment by AdamMc331** [comment] 2018-08-04 05:52
Hey @mustapha-hadid I've submit a PR for this! Let me know your initial thoughts. https://github.com/rstacruz/cheatsheets/pull/724

**Comment by AdamMc331** [comment] 2018-08-04 05:55
Also, any chance we can close this as a duplicate of #94?

**Comment by chadwithuhc** [comment] 2018-12-04 23:58
Duplicate of #94

**Closed by chadwithuhc** 2018-12-04 23:58 UTC
