### ISSUE TITLE
Cheatsheet request: kubernetes/kubectl

### ISSUE THREAD

**Issue by CorentinDy** [rstacruz/cheatsheets#711] opened 2018-08-02 13:42 UTC
https://files.acrobat.com/a/preview/5f7379e6-8331-4b90-ac64-691190c06ad3

**Comment by fmoliveira** [comment] 2018-08-09 14:37
@rstacruz This is duplicate of https://github.com/rstacruz/cheatsheets/issues/617

@CorentinDy I've added your suggested link in the original kubectl request 😃

**Closed** 2018-08-14 12:26 UTC
