### ISSUE TITLE
Cheatsheet request: kotlin

### ISSUE THREAD

**Issue by vladimir-petric** [rstacruz/cheatsheets#133] opened 2017-10-23 18:18 UTC

**Comment by AdamMc331** [comment] 2018-08-04 05:53
Hey @vladimir-petric Great idea! I've submit a PR, let me know what you think: https://github.com/rstacruz/cheatsheets/pull/724

**Comment by AdamMc331** [comment] 2018-08-04 05:55
Also, any chance we can close this as a duplicate of https://github.com/rstacruz/cheatsheets/issues/94?

**Comment by chadwithuhc** [comment] 2018-11-16 20:44
Closing in favor of #94

**Closed by chadwithuhc** 2018-11-16 20:44 UTC
