### ISSUE TITLE
Cheatsheet request: NGINX

### ISSUE THREAD

**Issue by rahulnetawat** [rstacruz/cheatsheets#595] opened 2018-07-04 09:57 UTC
Hello Buddy,

Thanks for the best collection. But i am looking for Nginx cheatsheet.
Please upload it fast.

**Comment by ricardobarantini** [comment] 2018-07-23 21:46
+1

**Comment by Natedeploys** [comment] 2018-10-18 18:17
+1

**Comment by chadwithuhc** [comment] 2018-12-05 00:03
Duplicate of #235

**Closed by chadwithuhc** 2018-12-05 00:03 UTC
