### ISSUE TITLE
Cheatsheet request: Symfony

### ISSUE THREAD

**Issue by aliemre** [rstacruz/cheatsheets#609] opened 2018-07-13 07:04 UTC
Hi,
Symfony is a set of PHP Components, a Web Application framework which is commonly used among PHP developers. It has many best practices and unknown features. I think it'd be good to add Symfony cheatsheet.

http://symfony.com/

**Comment by chadwithuhc** [comment] 2018-12-05 00:13
Duplicate of #272

**Closed by chadwithuhc** 2018-12-05 00:13 UTC
