### ISSUE TITLE
Cheatsheet request: VS-Code

### ISSUE THREAD

**Issue by Rajdeep97** [rstacruz/cheatsheets#216] opened 2017-11-01 14:00 UTC
Vs-Code is a new text editor like sublime by Microsoft. It would be great to have a cheat sheet for it.

**Comment by ZackNeyland** [comment] 2018-03-08 04:25
Looks to be a duplicate of... #112

**Comment by chadwithuhc** [comment] 2018-11-16 20:34
Closing in favor of original #71

**Closed by chadwithuhc** 2018-11-16 20:34 UTC
