### ISSUE TITLE
Cheatsheet request: KOTLIN

### ISSUE THREAD

**Issue by donpaul120** [rstacruz/cheatsheets#720] opened 2018-08-03 18:15 UTC
Kotlin Cheat Sheet will be a good one, i could assist with this if you want.

**Comment by AdamMc331** [comment] 2018-08-03 19:44
This would be great! I am more than happy to contribute to this as well. @donpaul120 Let me know if you'd like to collaborate on the content for it.

**Comment by AdamMc331** [comment] 2018-08-04 05:54
I got started on this. Let me know what you think: https://github.com/rstacruz/cheatsheets/pull/724

**Comment by AdamMc331** [comment] 2018-08-04 05:55
Also, any chance we can close this as a duplicate of #94?

**Comment by donpaul120** [comment] 2018-08-04 08:37
@AdamMc331 Sure... we can

**Comment by donpaul120** [comment] 2018-08-04 08:40
@AdamMc331  Nice on.. i got your message late.. You've pretty covered alot on it already.

**Comment by AdamMc331** [comment] 2018-08-04 15:13
Happy to hear any feedback though if you feel anything is missing. :)

**Comment by chadwithuhc** [comment] 2018-11-16 23:29
Duplicate of #94

**Closed by chadwithuhc** 2018-11-16 23:29 UTC
