### ISSUE TITLE
Cheatsheet request: APP_NAME_HERE

### ISSUE THREAD

**Issue by jfkm69** [rstacruz/cheatsheets#391] opened 2018-02-09 11:44 UTC
Hey,

I love the work you've done so far, devhints has been a great help.

Perhaps add PHP? I'd be more than willing to help get the content.

**Comment by hollasch** [comment] 2018-03-17 00:08
Duplicate of #75.

**Comment by rstacruz** [comment] 2018-03-17 04:56
thanks @hollasch for commenting!

**Closed by rstacruz** 2018-03-17 04:56 UTC
