### ISSUE TITLE
Cheatsheet request: emmet

### ISSUE THREAD

**Issue by daiyanze** [rstacruz/cheatsheets#539] opened 2018-05-24 01:58 UTC
I think it will be cool to have emmet cheat sheet! Thanks!

**Comment by danieljauch** [comment] 2018-08-08 23:06
New PR: https://github.com/rstacruz/cheatsheets/pull/737
👍

**Comment by chadwithuhc** [comment] 2018-12-04 23:33
Duplicate of #153

**Closed by chadwithuhc** 2018-12-04 23:33 UTC
